# Generated by Django 4.1.5 on 2023-01-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutactivitytrack',
            name='calorie_burnt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
