# Generated by Django 4.1.5 on 2023-01-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0002_workoutactivitytrack_calorie_burnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutactivitytrack',
            name='calorie_burnt',
            field=models.BigIntegerField(),
        ),
    ]
