# Generated by Django 4.1.5 on 2023-01-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0003_alter_workoutactivitytrack_calorie_burnt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='met_value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
