# Generated by Django 4.1.5 on 2023-01-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plan', '0004_alter_workouttype_met_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutactivitytrack',
            name='mins',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
